/**
 * Style Dictionary v5 config — generates CSS, TS, and JSON token outputs.
 * Uses DTCG ($value/$type) format.
 */
import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync, unlinkSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT = resolve(ROOT, "src/styles");

// ---------------------------------------------------------------------------
// Custom format: flat JSON with kebab-case keys (for Figma and TS generation)
// ---------------------------------------------------------------------------
StyleDictionary.registerFormat({
  name: "json/flat-kebab",
  format: ({ dictionary }) => {
    const result = {};
    dictionary.allTokens.forEach((token) => {
      result[token.name] = token.value ?? token.$value;
    });
    return JSON.stringify(result, null, 2) + "\n";
  },
});

// ---------------------------------------------------------------------------
// 1. Build base tokens
// ---------------------------------------------------------------------------
try {
  const base = new StyleDictionary({
    usesDtcg: true,
    source: [resolve(__dirname, "tokens.json")],
    platforms: {
      css: {
        prefix: "ds",
        transformGroup: "css",
        buildPath: `${OUT}/`,
        files: [
          {
            destination: "_base.css",
            format: "css/variables",
            options: { outputReferences: true },
          },
        ],
      },
      json: {
        prefix: "ds",
        transforms: ["attribute/cti", "name/kebab"],
        buildPath: `${OUT}/`,
        files: [
          {
            destination: "tokens.json",
            format: "json/flat-kebab",
          },
        ],
      },
    },
  });

  await base.buildAllPlatforms();
} catch {
  throw new Error("Token generation failed: unable to build base tokens");
}

// ---------------------------------------------------------------------------
// 2. Build dark theme overrides
// ---------------------------------------------------------------------------
try {
  const dark = new StyleDictionary({
    usesDtcg: true,
    source: [resolve(__dirname, "themes/dark.json")],
    platforms: {
      css: {
        prefix: "ds",
        transformGroup: "css",
        buildPath: `${OUT}/`,
        files: [
          {
            destination: "_dark.css",
            format: "css/variables",
            options: {
              outputReferences: true,
              selector: '[data-theme="dark"]',
            },
          },
        ],
      },
    },
  });

  await dark.buildAllPlatforms();
} catch {
  throw new Error("Token generation failed: unable to build dark theme");
}

// ---------------------------------------------------------------------------
// 3. Build high-contrast theme overrides
// ---------------------------------------------------------------------------
try {
  const hc = new StyleDictionary({
    usesDtcg: true,
    source: [resolve(__dirname, "themes/high-contrast.json")],
    platforms: {
      css: {
        prefix: "ds",
        transformGroup: "css",
        buildPath: `${OUT}/`,
        files: [
          {
            destination: "_high-contrast.css",
            format: "css/variables",
            options: {
              outputReferences: true,
              selector: '[data-theme="high-contrast"]',
            },
          },
        ],
      },
    },
  });

  await hc.buildAllPlatforms();
} catch {
  throw new Error("Token generation failed: unable to build high-contrast theme");
}

// ---------------------------------------------------------------------------
// 4. Merge CSS fragments into a single tokens.css
// ---------------------------------------------------------------------------
/** Read a generated CSS fragment by filename. */
function readFragment(filename) {
  try {
    return readFileSync(resolve(OUT, filename), "utf8");
  } catch {
    throw new Error(`Token generation failed: unable to read generated CSS fragment`);
  }
}

const header = `/**
 * Design Tokens — auto-generated by Style Dictionary.
 * Do not edit directly.
 */\n`;

const combined = [header, readFragment("_base.css"), readFragment("_dark.css"), readFragment("_high-contrast.css")].join(
  "\n",
);

try {
  writeFileSync(resolve(OUT, "tokens.css"), combined);
} catch {
  throw new Error("Token generation failed: unable to write combined CSS");
}

// Clean up fragments
for (const f of ["_base.css", "_dark.css", "_high-contrast.css"]) {
  try {
    unlinkSync(resolve(OUT, f));
  } catch {
    // Fragment already removed or never created — safe to ignore
  }
}

// ---------------------------------------------------------------------------
// 5. Generate typed TypeScript constants from the flat JSON
// ---------------------------------------------------------------------------
let flat;
try {
  flat = JSON.parse(readFragment("tokens.json"));
} catch {
  throw new Error("Token generation failed: unable to parse generated JSON");
}

/** Group flat tokens by category (first segment after prefix). */
function groupByCategory(obj) {
  const groups = {};
  for (const [key, value] of Object.entries(obj)) {
    const withoutPrefix = key.replace(/^ds-/, "");
    const dashIdx = withoutPrefix.indexOf("-");
    const cat = dashIdx === -1 ? withoutPrefix : withoutPrefix.slice(0, dashIdx);
    const rest = dashIdx === -1 ? withoutPrefix : withoutPrefix.slice(dashIdx + 1);
    if (!groups[cat]) groups[cat] = {};
    groups[cat][rest] = value;
  }
  return groups;
}

const grouped = groupByCategory(flat);

const tsLines = [
  "/**",
  " * Design Tokens — auto-generated by Style Dictionary.",
  " * Do not edit directly.",
  " */",
  "",
];

for (const [cat, values] of Object.entries(grouped)) {
  tsLines.push(`export const ${cat} = ${JSON.stringify(values, null, 2)} as const;`);
  tsLines.push("");
}

const catNames = Object.keys(grouped);
tsLines.push(
  `export const tokens = { ${catNames.join(", ")} } as const;`,
  "",
  "export type Tokens = typeof tokens;",
  "",
  "export default tokens;",
  "",
);

try {
  writeFileSync(resolve(OUT, "tokens.ts"), tsLines.join("\n"));
} catch {
  throw new Error("Token generation failed: unable to write TypeScript output");
}

console.log("Token generation complete");
